//
// Generated file, do not edit! Created by opp_msgc 4.1 from App_pck.msg.
//

#ifndef _APP_PCK_M_H_
#define _APP_PCK_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>App_pck.msg</tt> by opp_msgc.
 * <pre>
 * packet App_pck {
 * 
 * 
 * 
 * 
 * 	string data;
 * 	unsigned char dest[4];
 * }
 * </pre>
 */
class App_pck : public ::cPacket
{
  protected:
    opp_string data_var;
    unsigned char dest_var[4];

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const App_pck&);

  public:
    App_pck(const char *name=NULL, int kind=0);
    App_pck(const App_pck& other);
    virtual ~App_pck();
    App_pck& operator=(const App_pck& other);
    virtual App_pck *dup() const {return new App_pck(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getData() const;
    virtual void setData(const char * data_var);
    virtual unsigned int getDestArraySize() const;
    virtual unsigned char getDest(unsigned int k) const;
    virtual void setDest(unsigned int k, unsigned char dest_var);
};

inline void doPacking(cCommBuffer *b, App_pck& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, App_pck& obj) {obj.parsimUnpack(b);}


#endif // _APP_PCK_M_H_
