//
// Generated file, do not edit! Created by opp_msgc 4.1 from Arp.msg.
//

#ifndef _ARP_M_H_
#define _ARP_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>Arp.msg</tt> by opp_msgc.
 * <pre>
 * packet Arp {
 *    unsigned short type; 
 *    char ip[4];
 *    char mac[6];
 * }
 * </pre>
 */
class Arp : public ::cPacket
{
  protected:
    unsigned short type_var;
    char ip_var[4];
    char mac_var[6];

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Arp&);

  public:
    Arp(const char *name=NULL, int kind=0);
    Arp(const Arp& other);
    virtual ~Arp();
    Arp& operator=(const Arp& other);
    virtual Arp *dup() const {return new Arp(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned short getType() const;
    virtual void setType(unsigned short type_var);
    virtual unsigned int getIpArraySize() const;
    virtual char getIp(unsigned int k) const;
    virtual void setIp(unsigned int k, char ip_var);
    virtual unsigned int getMacArraySize() const;
    virtual char getMac(unsigned int k) const;
    virtual void setMac(unsigned int k, char mac_var);
};

inline void doPacking(cCommBuffer *b, Arp& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Arp& obj) {obj.parsimUnpack(b);}


#endif // _ARP_M_H_
