//
// Generated file, do not edit! Created by opp_msgc 4.1 from Eth_pck.msg.
//

#ifndef _ETH_PCK_M_H_
#define _ETH_PCK_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>Eth_pck.msg</tt> by opp_msgc.
 * <pre>
 * packet Eth_pck {
 * 
 * 
 * 
 * 
 * 
 *     
 *     string preamble;
 *     string macDest;
 *     string macSrc;
 *     short length;
 *     string data;
 * }
 * </pre>
 */
class Eth_pck : public ::cPacket
{
  protected:
    opp_string preamble_var;
    opp_string macDest_var;
    opp_string macSrc_var;
    short length_var;
    opp_string data_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Eth_pck&);

  public:
    Eth_pck(const char *name=NULL, int kind=0);
    Eth_pck(const Eth_pck& other);
    virtual ~Eth_pck();
    Eth_pck& operator=(const Eth_pck& other);
    virtual Eth_pck *dup() const {return new Eth_pck(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getPreamble() const;
    virtual void setPreamble(const char * preamble_var);
    virtual const char * getMacDest() const;
    virtual void setMacDest(const char * macDest_var);
    virtual const char * getMacSrc() const;
    virtual void setMacSrc(const char * macSrc_var);
    virtual short getLength() const;
    virtual void setLength(short length_var);
    virtual const char * getData() const;
    virtual void setData(const char * data_var);
};

inline void doPacking(cCommBuffer *b, Eth_pck& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Eth_pck& obj) {obj.parsimUnpack(b);}


#endif // _ETH_PCK_M_H_
