//
// Generated file, do not edit! Created by opp_msgc 4.1 from IP_pck.msg.
//

#ifndef _IP_PCK_M_H_
#define _IP_PCK_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>IP_pck.msg</tt> by opp_msgc.
 * <pre>
 * packet IP_pck {
 * 
 * 
 * 
 * 
 * 	string destIp;
 * 	string srcIp;
 * 	int checkSum;
 * 	int length;
 * 	
 * }
 * </pre>
 */
class IP_pck : public ::cPacket
{
  protected:
    opp_string destIp_var;
    opp_string srcIp_var;
    int checkSum_var;
    int length_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const IP_pck&);

  public:
    IP_pck(const char *name=NULL, int kind=0);
    IP_pck(const IP_pck& other);
    virtual ~IP_pck();
    IP_pck& operator=(const IP_pck& other);
    virtual IP_pck *dup() const {return new IP_pck(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getDestIp() const;
    virtual void setDestIp(const char * destIp_var);
    virtual const char * getSrcIp() const;
    virtual void setSrcIp(const char * srcIp_var);
    virtual int getCheckSum() const;
    virtual void setCheckSum(int checkSum_var);
    virtual int getLength() const;
    virtual void setLength(int length_var);
};

inline void doPacking(cCommBuffer *b, IP_pck& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, IP_pck& obj) {obj.parsimUnpack(b);}


#endif // _IP_PCK_M_H_
